---
## To call this playbook:
##    ansible-playbook -i hosts show_hostname_vyos.yml
- name: Show current hostnames
  hosts: vyosrouters
  gather_facts: no

  tasks:
    - name: gather facts from managed vyos nodes
      vyos_facts:
        gather_subset: all

    - name: Output some of the gathered facts
      debug:
        msg: "Managed Node '{{inventory_hostname}}' has hostname '{{ansible_net_hostname}}' and OS-Version '{{ansible_net_version}}'."
